# stuff needed to enable routing

- name: OpenBSD sysctl net.inet.ip.forwarding = 1 enable ipv4 forwarding
  sysctl: name=net.inet.ip.forwarding value=1 reload=no sysctl_set=yes
  tags:
  - sysctl

- name: OpenBSD sysctl net.inet.ip.forwarding = 1 enable ipv4 forwarding (live)
  shell: /usr/sbin/sysctl net.inet.ip.forwarding=1

- name: copy rc.conf.local to servers
  copy: src=network/rc.conf.local dest=/etc/rc.conf.local owner=root group=wheel mode=0644

- name: setting default gw
  template: 
    src=mygate.j2 dest=/etc/mygate 
    owner=root group=wheel mode=0644
  notify:
  - reload network
  when: LAN_params[NAT_outside].gateway is defined
  
- name: remove default gw config
  file: path=/etc/mygate state=absent
  when: LAN_params[NAT_outside].gateway is not defined
  
- name: copy unbound.conf
  copy: src=network/unbound.conf dest=/var/unbound/etc/unbound.conf owner=root group=wheel mode=0644
  notify:
  - restart unbound

# /etc/mygate is not working due to dhcp...
- name: add default gw to route
  template: src=hostname.ext_if.j2 dest=/etc/hostname.{{ item }} owner=root group=wheel mode=0600
  with_items: "{{ ip_addresses | list }}"
  notify:
  - reload network

- name: dhclient configuration
  copy: src=network/dhclient.conf dest=/etc/dhclient.conf owner=root group=wheel mode=0644
  notify:
  - reload network
  
- name: configure dhcpd interfaces
  template: src=dhcpd.interfaces.j2 dest=/etc/dhcpd.interfaces owner=root group=wheel mode=0644
  notify:
  - restart dhcpd
  
- name: configure dhcpd
  template: src=dhcpd.conf.j2 dest=/etc/dhcpd.conf owner=root group=wheel mode=0644
  notify:
  - restart dhcpd
  
# ips must be working before pf is started  
- name: copy PF pf.conf
  template: src=pf.conf.j2 dest=/etc/pf.conf owner=root group=wheel mode=0600
  notify:
  - reload pf
  
