# includes relevant handlers

# TODO: move this to a separate file

- name: restart unbound
  service: name=unbound state=restarted
    
- name: reload network
  action: shell /bin/sh /etc/netstart
    
- name: restart dhcpd
  service: name=dhcpd state=restarted

- name: reload pf
  action: shell /sbin/pfctl -f /etc/pf.conf
    
